/**
 * demo_sequences.h — AUTO-GENERATED by extract_demo_data.py
 * DO NOT EDIT MANUALLY.
 * 100 demo samples extracted from Indoor Fire Dataset:
 *   BG(50) → Fire(50)
 *
 * Sensor order in kDemoData[step][10]:
 *   [0] CO      [1] H2       [2] Humidity  [3] PM05     [4] PM10
 *   [5] PM_Typ  [6] PM_Total [7] Temp      [8] UV        [9] VOC
 */

#pragma once
#include <Arduino.h>

// ── Demo metadata ─────────────────────────────────────────────────────────────
constexpr int kDemoTotalSteps = 100;

// Ground truth label per step: 0=Background, 1=Fire, 2=Nuisance
const uint8_t kDemoLabels[100] PROGMEM = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 };

// Transition points: step index where label changes
constexpr int kDemoTransitionCount = 2;
constexpr int kDemoTransitionSteps[2] = { 0, 50 };
const char* const kDemoTransitionNames[2] = { "Background", "Fire" };

// ── Sensor data ───────────────────────────────────────────────────────────────
// kDemoData[100][10]: 10 raw sensor values per step (pre-scaler, pre-feature-engineering)
// FireDetector::push() computes 28 features internally from these 10 values.
// Memory: 100 × 10 × 4 bytes = 4000 bytes flash
const float kDemoData[100][10] PROGMEM = {
    // ── Phase: Background ──
  { 0.86f, -0.39f, 40.17f, 2.0f, 0.0f, 0.41f, 2.0f, 25.8f, 1.0f, 0.2f },  // step   0 | GT: Background
  { 1.1f, 0.26f, 41.9f, 2.0f, 0.0f, 0.37f, 2.0f, 25.3f, 0.0f, 0.3f },  // step   1 | GT: Background
  { 0.8f, 0.13f, 42.83f, 4.0f, 0.0f, 0.37f, 5.0f, 24.6f, 0.0f, 0.3f },  // step   2 | GT: Background
  { 0.14f, -0.1f, 42.46f, 4.0f, 0.0f, 0.37f, 4.0f, 24.7f, 0.0f, 0.0f },  // step   3 | GT: Background
  { 0.13f, -0.38f, 41.57f, 4.0f, 0.0f, 0.4f, 5.0f, 25.4f, 0.0f, 0.4f },  // step   4 | GT: Background
  { 0.48f, 0.08f, 41.27f, 3.0f, 0.0f, 0.39f, 4.0f, 25.7f, 0.0f, 0.1f },  // step   5 | GT: Background
  { -0.07f, 0.1f, 40.64f, 2.0f, 0.0f, 0.39f, 3.0f, 25.6f, 0.0f, -0.0f },  // step   6 | GT: Background
  { 0.62f, 0.03f, 41.8f, 1.0f, 0.0f, 0.37f, 2.0f, 25.0f, 0.0f, 0.2f },  // step   7 | GT: Background
  { 0.57f, -0.06f, 42.37f, 4.0f, 0.0f, 0.37f, 4.0f, 25.0f, 0.0f, 0.3f },  // step   8 | GT: Background
  { 0.89f, -0.37f, 40.18f, 3.0f, 0.0f, 0.41f, 3.0f, 25.8f, 0.0f, 0.2f },  // step   9 | GT: Background
  { 1.19f, 0.24f, 41.94f, 1.0f, 0.0f, 0.37f, 2.0f, 25.3f, 0.0f, 0.3f },  // step  10 | GT: Background
  { 0.7f, 0.12f, 42.83f, 4.0f, 0.0f, 0.37f, 5.0f, 24.6f, 0.0f, 0.3f },  // step  11 | GT: Background
  { 0.14f, -0.11f, 42.47f, 3.0f, 0.0f, 0.37f, 3.0f, 24.7f, 0.0f, 0.0f },  // step  12 | GT: Background
  { 0.1f, -0.36f, 41.52f, 4.0f, 0.0f, 0.4f, 5.0f, 25.4f, 0.0f, 0.5f },  // step  13 | GT: Background
  { 0.51f, 0.09f, 41.28f, 4.0f, 0.0f, 0.39f, 4.0f, 25.7f, 0.0f, 0.1f },  // step  14 | GT: Background
  { -0.1f, 0.09f, 40.76f, 3.0f, 0.0f, 0.39f, 3.0f, 25.6f, 0.0f, -0.0f },  // step  15 | GT: Background
  { 0.54f, 0.02f, 41.83f, 2.0f, 0.0f, 0.37f, 3.0f, 25.0f, 0.0f, 0.2f },  // step  16 | GT: Background
  { 0.55f, -0.07f, 42.37f, 3.0f, 0.0f, 0.37f, 4.0f, 25.0f, 0.0f, 0.3f },  // step  17 | GT: Background
  { 0.85f, -0.46f, 40.17f, 4.0f, 0.0f, 0.41f, 4.0f, 25.8f, 0.0f, 0.2f },  // step  18 | GT: Background
  { 1.19f, 0.24f, 41.93f, 1.0f, 0.0f, 0.37f, 2.0f, 25.3f, 0.0f, 0.3f },  // step  19 | GT: Background
  { 0.68f, 0.14f, 42.87f, 4.0f, 0.0f, 0.37f, 4.0f, 24.6f, 0.0f, 0.3f },  // step  20 | GT: Background
  { 0.19f, -0.09f, 42.49f, 2.0f, 0.0f, 0.37f, 2.0f, 24.7f, 0.0f, 0.0f },  // step  21 | GT: Background
  { 0.08f, -0.37f, 41.52f, 4.0f, 0.0f, 0.4f, 5.0f, 25.4f, 0.0f, 0.4f },  // step  22 | GT: Background
  { 0.51f, 0.08f, 41.28f, 3.0f, 0.0f, 0.39f, 4.0f, 25.7f, 0.0f, 0.1f },  // step  23 | GT: Background
  { -0.13f, 0.11f, 40.81f, 4.0f, 0.0f, 0.39f, 5.0f, 25.6f, 0.0f, -0.0f },  // step  24 | GT: Background
  { 0.53f, 0.03f, 41.8f, 3.0f, 0.0f, 0.37f, 4.0f, 25.0f, 0.0f, 0.2f },  // step  25 | GT: Background
  { 0.57f, -0.07f, 42.37f, 4.0f, 0.0f, 0.37f, 4.0f, 25.0f, 0.0f, 0.3f },  // step  26 | GT: Background
  { 0.9f, -0.4f, 40.16f, 3.0f, 0.0f, 0.41f, 3.0f, 25.8f, 0.0f, 0.2f },  // step  27 | GT: Background
  { 1.12f, 0.24f, 41.92f, 1.0f, 0.0f, 0.37f, 1.0f, 25.3f, 0.0f, 0.3f },  // step  28 | GT: Background
  { 0.74f, 0.12f, 42.87f, 4.0f, 0.0f, 0.37f, 4.0f, 24.6f, 0.0f, 0.3f },  // step  29 | GT: Background
  { 0.23f, -0.1f, 42.5f, 3.0f, 0.0f, 0.37f, 3.0f, 24.7f, 0.0f, 0.0f },  // step  30 | GT: Background
  { 0.08f, -0.33f, 41.51f, 4.0f, 0.0f, 0.4f, 5.0f, 25.4f, 1.0f, 0.5f },  // step  31 | GT: Background
  { 0.47f, 0.07f, 41.29f, 4.0f, 0.0f, 0.39f, 4.0f, 25.7f, 0.0f, 0.1f },  // step  32 | GT: Background
  { -0.08f, 0.1f, 40.75f, 4.0f, 0.0f, 0.39f, 5.0f, 25.6f, 0.0f, -0.0f },  // step  33 | GT: Background
  { 0.55f, 0.03f, 41.78f, 3.0f, 0.0f, 0.37f, 3.0f, 25.0f, 0.0f, 0.2f },  // step  34 | GT: Background
  { 0.56f, -0.05f, 42.36f, 4.0f, 0.0f, 0.37f, 4.0f, 25.0f, 0.0f, 0.3f },  // step  35 | GT: Background
  { 0.88f, -0.42f, 40.16f, 2.0f, 0.0f, 0.41f, 2.0f, 25.8f, 0.0f, 0.2f },  // step  36 | GT: Background
  { 1.08f, 0.25f, 41.9f, 1.0f, 0.0f, 0.37f, 1.0f, 25.3f, 0.0f, 0.3f },  // step  37 | GT: Background
  { 0.65f, 0.15f, 42.84f, 4.0f, 0.0f, 0.37f, 4.0f, 24.6f, 0.0f, 0.3f },  // step  38 | GT: Background
  { 0.28f, -0.13f, 42.49f, 5.0f, 0.0f, 0.37f, 5.0f, 24.7f, 0.0f, 0.0f },  // step  39 | GT: Background
  { 0.08f, -0.34f, 41.49f, 4.0f, 0.0f, 0.4f, 4.0f, 25.4f, 0.0f, 0.4f },  // step  40 | GT: Background
  { 0.42f, 0.07f, 41.26f, 4.0f, 0.0f, 0.4f, 5.0f, 25.7f, 0.0f, 0.1f },  // step  41 | GT: Background
  { -0.16f, 0.07f, 40.68f, 4.0f, 0.0f, 0.39f, 4.0f, 25.6f, 0.0f, 0.0f },  // step  42 | GT: Background
  { 0.5f, 0.03f, 41.81f, 2.0f, 0.0f, 0.37f, 3.0f, 25.0f, 0.0f, 0.2f },  // step  43 | GT: Background
  { 0.43f, -0.05f, 42.32f, 3.0f, 0.0f, 0.37f, 4.0f, 25.0f, 0.0f, 0.3f },  // step  44 | GT: Background
  { 0.88f, -0.44f, 40.17f, 1.0f, 0.0f, 0.41f, 1.0f, 25.8f, 0.0f, 0.3f },  // step  45 | GT: Background
  { 1.05f, 0.29f, 41.89f, 1.0f, 0.0f, 0.37f, 1.0f, 25.3f, 0.0f, 0.3f },  // step  46 | GT: Background
  { 0.67f, 0.13f, 42.85f, 4.0f, 0.0f, 0.37f, 5.0f, 24.6f, 0.0f, 0.3f },  // step  47 | GT: Background
  { 0.22f, -0.11f, 42.46f, 6.0f, 0.0f, 0.37f, 7.0f, 24.7f, 0.0f, 0.1f },  // step  48 | GT: Background
  { 0.01f, -0.37f, 41.48f, 4.0f, 0.0f, 0.4f, 5.0f, 25.4f, 0.0f, 0.4f },  // step  49 | GT: Background
    // ── Phase: Fire ──
  { 0.67f, 0.28f, 41.86f, 3.0f, 0.0f, 0.37f, 3.0f, 25.4f, 55.0f, 0.5f },  // step  50 | GT: Fire
  { 0.44f, 0.15f, 43.08f, 4.0f, 0.0f, 0.38f, 5.0f, 24.6f, 45.0f, 0.4f },  // step  51 | GT: Fire
  { -0.3f, -0.04f, 42.72f, 6.0f, 0.0f, 0.38f, 7.0f, 24.7f, 50.0f, 0.2f },  // step  52 | GT: Fire
  { -0.08f, -0.37f, 42.34f, 5.0f, 0.0f, 0.4f, 6.0f, 25.4f, 186.0f, 0.5f },  // step  53 | GT: Fire
  { 0.13f, 0.09f, 41.15f, 2.0f, 0.0f, 0.38f, 3.0f, 25.8f, 111.0f, 0.2f },  // step  54 | GT: Fire
  { -0.63f, 0.07f, 40.75f, 4.0f, 0.0f, 0.4f, 5.0f, 25.7f, 0.0f, 0.1f },  // step  55 | GT: Fire
  { 0.26f, 0.06f, 41.85f, 2.0f, 0.0f, 0.39f, 3.0f, 25.1f, 49.0f, 0.3f },  // step  56 | GT: Fire
  { 0.23f, -0.03f, 42.17f, 2.0f, 0.0f, 0.37f, 2.0f, 25.2f, 2.0f, 0.5f },  // step  57 | GT: Fire
  { 0.66f, -0.44f, 40.44f, 3.0f, 0.0f, 0.4f, 3.0f, 25.8f, 0.0f, 0.4f },  // step  58 | GT: Fire
  { 0.71f, 0.25f, 41.85f, 3.0f, 0.0f, 0.37f, 3.0f, 25.5f, 128.0f, 0.5f },  // step  59 | GT: Fire
  { 0.48f, 0.17f, 43.08f, 4.0f, 0.0f, 0.38f, 5.0f, 24.6f, 65.0f, 0.4f },  // step  60 | GT: Fire
  { -0.21f, -0.08f, 42.73f, 6.0f, 0.0f, 0.38f, 7.0f, 24.7f, 76.0f, 0.2f },  // step  61 | GT: Fire
  { -0.03f, -0.33f, 42.27f, 5.0f, 0.0f, 0.4f, 6.0f, 25.4f, 291.0f, 0.5f },  // step  62 | GT: Fire
  { 0.18f, 0.1f, 41.16f, 3.0f, 0.0f, 0.38f, 3.0f, 25.8f, 170.0f, 0.3f },  // step  63 | GT: Fire
  { -0.65f, 0.13f, 40.92f, 4.0f, 0.0f, 0.4f, 5.0f, 25.7f, 1.0f, 0.1f },  // step  64 | GT: Fire
  { 0.26f, 0.06f, 41.89f, 3.0f, 0.0f, 0.39f, 3.0f, 25.1f, 70.0f, 0.3f },  // step  65 | GT: Fire
  { 0.26f, -0.03f, 42.18f, 2.0f, 0.0f, 0.37f, 2.0f, 25.2f, 17.0f, 0.5f },  // step  66 | GT: Fire
  { 0.69f, -0.43f, 40.39f, 3.0f, 0.0f, 0.4f, 3.0f, 25.8f, 66.0f, 0.4f },  // step  67 | GT: Fire
  { 0.7f, 0.26f, 41.88f, 3.0f, 0.0f, 0.37f, 3.0f, 25.4f, 119.0f, 0.5f },  // step  68 | GT: Fire
  { 0.46f, 0.17f, 43.06f, 4.0f, 0.0f, 0.38f, 4.0f, 24.6f, 64.0f, 0.4f },  // step  69 | GT: Fire
  { -0.15f, -0.07f, 42.77f, 6.0f, 0.0f, 0.39f, 7.0f, 24.6f, 76.0f, 0.2f },  // step  70 | GT: Fire
  { -0.07f, -0.35f, 41.96f, 6.0f, 0.0f, 0.4f, 7.0f, 25.4f, 288.0f, 0.5f },  // step  71 | GT: Fire
  { 0.21f, 0.09f, 41.18f, 2.0f, 0.0f, 0.38f, 3.0f, 25.8f, 184.0f, 0.2f },  // step  72 | GT: Fire
  { -0.58f, 0.09f, 40.86f, 5.0f, 0.0f, 0.4f, 6.0f, 25.8f, 1.0f, 0.1f },  // step  73 | GT: Fire
  { 0.26f, 0.06f, 41.89f, 3.0f, 0.0f, 0.39f, 3.0f, 25.1f, 66.0f, 0.3f },  // step  74 | GT: Fire
  { 0.25f, -0.03f, 42.19f, 2.0f, 0.0f, 0.38f, 2.0f, 25.2f, 34.0f, 0.5f },  // step  75 | GT: Fire
  { 0.65f, -0.43f, 40.5f, 3.0f, 0.0f, 0.4f, 3.0f, 25.8f, 90.0f, 0.4f },  // step  76 | GT: Fire
  { 0.63f, 0.28f, 41.86f, 2.0f, 0.0f, 0.37f, 2.0f, 25.4f, 122.0f, 0.5f },  // step  77 | GT: Fire
  { 0.55f, 0.19f, 43.03f, 3.0f, 0.0f, 0.38f, 4.0f, 24.6f, 62.0f, 0.5f },  // step  78 | GT: Fire
  { -0.18f, -0.07f, 42.8f, 6.0f, 0.0f, 0.39f, 6.0f, 24.6f, 76.0f, 0.2f },  // step  79 | GT: Fire
  { 0.0f, -0.28f, 41.81f, 6.0f, 0.0f, 0.4f, 7.0f, 25.4f, 272.0f, 0.5f },  // step  80 | GT: Fire
  { 0.25f, 0.09f, 41.16f, 2.0f, 0.0f, 0.38f, 2.0f, 25.8f, 153.0f, 0.2f },  // step  81 | GT: Fire
  { -0.6f, 0.12f, 40.67f, 6.0f, 0.0f, 0.4f, 7.0f, 25.8f, 2.0f, 0.1f },  // step  82 | GT: Fire
  { 0.27f, 0.06f, 41.91f, 3.0f, 0.0f, 0.38f, 3.0f, 25.1f, 70.0f, 0.3f },  // step  83 | GT: Fire
  { 0.22f, -0.02f, 42.2f, 3.0f, 0.0f, 0.38f, 4.0f, 25.2f, 27.0f, 0.5f },  // step  84 | GT: Fire
  { 0.7f, -0.42f, 40.52f, 3.0f, 0.0f, 0.4f, 3.0f, 25.8f, 86.0f, 0.4f },  // step  85 | GT: Fire
  { 0.62f, 0.29f, 41.88f, 2.0f, 0.0f, 0.37f, 2.0f, 25.4f, 152.0f, 0.5f },  // step  86 | GT: Fire
  { 0.61f, 0.18f, 43.02f, 3.0f, 0.0f, 0.38f, 4.0f, 24.6f, 64.0f, 0.4f },  // step  87 | GT: Fire
  { -0.28f, -0.08f, 42.8f, 5.0f, 0.0f, 0.39f, 5.0f, 24.6f, 70.0f, 0.2f },  // step  88 | GT: Fire
  { 0.03f, -0.29f, 41.77f, 7.0f, 1.0f, 0.4f, 9.0f, 25.4f, 276.0f, 0.5f },  // step  89 | GT: Fire
  { 0.22f, 0.08f, 41.16f, 2.0f, 0.0f, 0.38f, 3.0f, 25.8f, 223.0f, 0.2f },  // step  90 | GT: Fire
  { -0.55f, 0.12f, 40.61f, 6.0f, 0.0f, 0.4f, 7.0f, 25.8f, 0.0f, 0.1f },  // step  91 | GT: Fire
  { 0.24f, 0.05f, 41.91f, 3.0f, 0.0f, 0.38f, 4.0f, 25.1f, 65.0f, 0.3f },  // step  92 | GT: Fire
  { 0.2f, -0.03f, 42.21f, 3.0f, 0.0f, 0.38f, 4.0f, 25.2f, 33.0f, 0.5f },  // step  93 | GT: Fire
  { 0.69f, -0.43f, 40.44f, 2.0f, 0.0f, 0.4f, 3.0f, 25.8f, 105.0f, 0.4f },  // step  94 | GT: Fire
  { 0.6f, 0.28f, 41.88f, 2.0f, 0.0f, 0.37f, 2.0f, 25.4f, 125.0f, 0.5f },  // step  95 | GT: Fire
  { 0.67f, 0.19f, 43.04f, 3.0f, 0.0f, 0.38f, 4.0f, 24.6f, 66.0f, 0.4f },  // step  96 | GT: Fire
  { -0.24f, -0.1f, 42.8f, 4.0f, 0.0f, 0.39f, 5.0f, 24.7f, 85.0f, 0.2f },  // step  97 | GT: Fire
  { 0.0f, -0.35f, 41.71f, 7.0f, 1.0f, 0.4f, 8.0f, 25.5f, 287.0f, 0.5f },  // step  98 | GT: Fire
  { 0.17f, 0.09f, 41.17f, 3.0f, 0.0f, 0.38f, 4.0f, 25.8f, 209.0f, 0.3f }  // step  99 | GT: Fire
};
