// Auto-generated by convert_model.py — DO NOT EDIT
// Run:  python firmware/convert_model.py
#pragma once
#include <cstdint>

constexpr int kNumFeatures = 28;
constexpr int kWindowSize  = 18;
constexpr int kNumClasses  = 3;

// ── Feature indices ───────────────────────────────────────────────────────
constexpr int kFeat_CO_ROOM = 0;
constexpr int kFeat_H2_ROOM = 1;
constexpr int kFeat_HUMIDITY_ROOM = 2;
constexpr int kFeat_PM05_ROOM = 3;
constexpr int kFeat_PM10_ROOM = 4;
constexpr int kFeat_PM_ROOM_TYPICAL_SIZE = 5;
constexpr int kFeat_PM_TOTAL_ROOM = 6;
constexpr int kFeat_TEMPERATURE_ROOM = 7;
constexpr int kFeat_UV_ROOM = 8;
constexpr int kFeat_VOC_ROOM_RAW = 9;
constexpr int kFeat_DELTA_CO_ROOM = 10;
constexpr int kFeat_DELTA_H2_ROOM = 11;
constexpr int kFeat_DELTA_PM05_ROOM = 12;
constexpr int kFeat_DELTA_PM_TOTAL_ROOM = 13;
constexpr int kFeat_DELTA_VOC_ROOM_RAW = 14;
constexpr int kFeat_ROLL_MEAN_CO_ROOM = 15;
constexpr int kFeat_ROLL_MEAN_H2_ROOM = 16;
constexpr int kFeat_ROLL_MEAN_PM05_ROOM = 17;
constexpr int kFeat_ROLL_MEAN_PM_TOTAL_ROOM = 18;
constexpr int kFeat_ROLL_MEAN_VOC_ROOM_RAW = 19;
constexpr int kFeat_ROLL_STD_CO_ROOM = 20;
constexpr int kFeat_ROLL_STD_H2_ROOM = 21;
constexpr int kFeat_ROLL_STD_PM05_ROOM = 22;
constexpr int kFeat_ROLL_STD_PM_TOTAL_ROOM = 23;
constexpr int kFeat_ROLL_STD_VOC_ROOM_RAW = 24;
constexpr int kFeat_VOC_CO_RATIO = 25;
constexpr int kFeat_PM_SIZE_RATIO = 26;
constexpr int kFeat_UV_NORM = 27;

// ── StandardScaler parameters ────────────────────────────────────────────
// normalize: x_scaled = (x_raw - mean) * std_inv
const float kScalerMean[28] = {
  0.23732249f, 0.20375667f, 43.93713109f, 1014.29680573f,
  200.99864432f, 0.43815274f, 1256.40245201f, 25.38163431f,
  1.92393030f, 1.87825606f, 0.00005284f, -0.00000164f,
  -0.00030313f, -0.00033260f, 0.00001474f, 0.23718878f,
  0.20376159f, 1014.29755283f, 1256.40326416f, 1.87821618f,
  0.05517988f, 0.02168743f, 84.70352141f, 110.51778669f,
  0.05299207f, 4.37554897f, 0.05335258f, 0.00526296f,
};

const float kScalerStdInv[28] = {
  1.06934145f, 1.61668132f, 0.30813736f, 0.00022721f,
  0.00097002f, 12.18434167f, 0.00017836f, 1.75599588f,
  0.04687022f, 0.36665152f, 11.60362086f, 26.29573882f,
  0.00220692f, 0.00163276f, 4.43353082f, 1.07569087f,
  1.61980625f, 0.00022829f, 0.00017943f, 0.36824648f,
  10.49468129f, 27.75853836f, 0.00216702f, 0.00151157f,
  3.66548555f, 0.21693798f, 25.99752006f, 17.92628812f,
};

// Feature names (for debug logging)
const char* const kFeatureNames[28] = {
  "CO_Room",
  "H2_Room",
  "Humidity_Room",
  "PM05_Room",
  "PM10_Room",
  "PM_Room_Typical_Size",
  "PM_Total_Room",
  "Temperature_Room",
  "UV_Room",
  "VOC_Room_RAW",
  "delta_CO_Room",
  "delta_H2_Room",
  "delta_PM05_Room",
  "delta_PM_Total_Room",
  "delta_VOC_Room_RAW",
  "roll_mean_CO_Room",
  "roll_mean_H2_Room",
  "roll_mean_PM05_Room",
  "roll_mean_PM_Total_Room",
  "roll_mean_VOC_Room_RAW",
  "roll_std_CO_Room",
  "roll_std_H2_Room",
  "roll_std_PM05_Room",
  "roll_std_PM_Total_Room",
  "roll_std_VOC_Room_RAW",
  "VOC_CO_ratio",
  "PM_size_ratio",
  "UV_norm",
};