"""
Convert CNN1D Keras model → TFLite INT8 → C header files for ESP32 deployment.

Run ONCE on PC/server before flashing firmware:
    cd <project_root>
    python firmware/convert_model.py

Output (auto-generated, do not edit manually):
    firmware/src/model_data.h    — TFLite flatbuffer as uint8_t[] in flash
    firmware/src/scaler_params.h — StandardScaler mean/std for normalization

CNN1D architecture (100,339 params):
    Input (18, 28)
    → BatchNorm
    → Conv1D(64, k=3, same, relu) × 2 → AvgPool(2) → (9, 64)
    → Conv1D(128, k=3, same, relu) × 2 → GlobalAvgPool → (128,)
    → Dense(64, relu) → Dense(3, softmax)

TFLite ops used: CONV_2D, AVERAGE_POOL_2D, MEAN, FULLY_CONNECTED, SOFTMAX, RESHAPE
"""

import os
import sys
import pathlib
import numpy as np

# ── Paths (relative to project root) ──────────────────────────────────────
ROOT        = pathlib.Path(__file__).parent.parent
MODEL_PATH  = ROOT / "services/ml_service/saved_models/cnn1d_indoor.keras"
SCALER_PATH = ROOT / "services/ml_service/saved_models/scaler_indoor.pkl"
FEAT_PATH   = ROOT / "services/ml_service/saved_models/feature_cols_indoor.pkl"
OUT_MODEL   = ROOT / "firmware/src/model_data.h"
OUT_SCALER  = ROOT / "firmware/src/scaler_params.h"

# ── Check dependencies ─────────────────────────────────────────────────────
try:
    import tensorflow as tf
    import joblib
except ImportError as e:
    sys.exit(f"[ERROR] Missing dependency: {e}\n  pip install tensorflow joblib")

print(f"TensorFlow {tf.__version__}")

# ── Load Keras model & artifacts ───────────────────────────────────────────
print("\n[1/4] Loading Keras model...")
model = tf.keras.models.load_model(str(MODEL_PATH), compile=False)
model.summary()

window_size, n_features = model.input_shape[1], model.input_shape[2]
n_classes = model.output_shape[-1]
print(f"      Input shape : ({window_size}, {n_features})")
print(f"      Output shape: ({n_classes},)  — Background / Fire / Nuisance")

print("\n[2/4] Loading scaler & feature list...")
scaler       = joblib.load(str(SCALER_PATH))
feature_cols = joblib.load(str(FEAT_PATH))
assert len(feature_cols) == n_features, "Feature count mismatch!"
print(f"      {n_features} features loaded")


# ── Representative dataset for INT8 calibration ────────────────────────────
# Inputs must be post-scaler (i.e. mean=0, std=1) because the model
# receives already-normalized data.  We simulate from N(0,1).
def representative_dataset():
    rng = np.random.default_rng(42)
    for _ in range(300):
        x = rng.normal(0.0, 1.0, size=(1, window_size, n_features)).astype(np.float32)
        yield [x]


# ── TFLite INT8 full-integer conversion ────────────────────────────────────
print("\n[3/4] Converting to TFLite INT8 (full-integer)...")
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations               = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset      = representative_dataset
converter.target_spec.supported_ops   = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type        = tf.int8
converter.inference_output_type       = tf.int8

tflite_model = converter.convert()
size_kb = len(tflite_model) / 1024
print(f"      TFLite model size: {size_kb:.1f} KB  (was {os.path.getsize(MODEL_PATH)/1024:.0f} KB float32)")


# ── Write model_data.h ─────────────────────────────────────────────────────
def write_model_header(path: pathlib.Path, data: bytes):
    lines = [
        "// Auto-generated by convert_model.py — DO NOT EDIT",
        "// Run:  python firmware/convert_model.py",
        "#pragma once",
        "#include <cstdint>",
        "",
        f"// CNN1D INT8 TFLite flatbuffer  ({len(data) / 1024:.1f} KB)",
        f"constexpr unsigned int kCnn1dModelLen = {len(data)}u;",
        "alignas(8) const uint8_t kCnn1dModelData[] = {",
    ]
    hex_bytes = []
    for i, b in enumerate(data):
        hex_bytes.append(f"0x{b:02x}")
        if (i + 1) % 16 == 0:
            hex_bytes.append("\n  ")
    lines.append("  " + ", ".join(hex_bytes))
    lines.append("};")
    path.write_text("\n".join(lines))


print(f"\n[4/4] Writing header files...")
write_model_header(OUT_MODEL, tflite_model)
print(f"      {OUT_MODEL}  ({size_kb:.1f} KB)")


# ── Write scaler_params.h ──────────────────────────────────────────────────
mean_arr    = scaler.mean_
std_arr     = np.sqrt(scaler.var_)
std_inv_arr = 1.0 / (std_arr + 1e-8)  # pre-computed inverse for fast normalization

header_lines = [
    "// Auto-generated by convert_model.py — DO NOT EDIT",
    "// Run:  python firmware/convert_model.py",
    "#pragma once",
    "#include <cstdint>",
    "",
    f"constexpr int kNumFeatures = {n_features};",
    f"constexpr int kWindowSize  = {window_size};",
    f"constexpr int kNumClasses  = {n_classes};",
    "",
    "// Feature index constants",
]
for i, name in enumerate(feature_cols):
    safe_name = name.upper().replace(" ", "_")
    header_lines.append(f"constexpr int kFeat_{safe_name} = {i};")

header_lines += [
    "",
    "// StandardScaler — mean (subtract before dividing by std)",
    f"const float kScalerMean[{n_features}] = {{",
]
for i, v in enumerate(mean_arr):
    suffix = "\n  " if (i + 1) % 4 == 0 else " "
    header_lines[-1] += f"\n  {v:.8f}f," if i == 0 else ""
    if i == 0:
        header_lines.append(f"  {v:.8f}f,")
    else:
        header_lines[-1] += f" {v:.8f}f,"
        if (i + 1) % 4 == 0:
            header_lines.append("  ")

# Cleaner approach for arrays:
def fmt_float_array(name, values, n_per_line=4):
    rows = [f"const float {name}[{len(values)}] = {{"]
    chunk = []
    for v in values:
        chunk.append(f"{v:.8f}f")
        if len(chunk) == n_per_line:
            rows.append("  " + ", ".join(chunk) + ",")
            chunk = []
    if chunk:
        rows.append("  " + ", ".join(chunk) + ",")
    rows.append("};")
    return "\n".join(rows)

scaler_lines = [
    "// Auto-generated by convert_model.py — DO NOT EDIT",
    "// Run:  python firmware/convert_model.py",
    "#pragma once",
    "#include <cstdint>",
    "",
    f"constexpr int kNumFeatures = {n_features};",
    f"constexpr int kWindowSize  = {window_size};",
    f"constexpr int kNumClasses  = {n_classes};",
    "",
    "// ── Feature indices ───────────────────────────────────────────────────────",
]
for i, name in enumerate(feature_cols):
    safe = "kFeat_" + name.upper().replace(" ", "_").replace(".", "_")
    scaler_lines.append(f"constexpr int {safe} = {i};")

scaler_lines += [
    "",
    "// ── StandardScaler parameters ────────────────────────────────────────────",
    "// normalize: x_scaled = (x_raw - mean) * std_inv",
    fmt_float_array("kScalerMean", mean_arr),
    "",
    fmt_float_array("kScalerStdInv", std_inv_arr),
    "",
    "// Feature names (for debug logging)",
    f"const char* const kFeatureNames[{n_features}] = {{",
]
for name in feature_cols:
    scaler_lines.append(f'  "{name}",')
scaler_lines.append("};")

OUT_SCALER.write_text("\n".join(scaler_lines))
print(f"      {OUT_SCALER}")

print("\n=== Done ===")
print(f"Model size after INT8 quantization: {size_kb:.1f} KB")
print(f"Estimated activation arena needed:  ~40-50 KB")
print(f"Total additional RAM on ESP32:      ~50 KB")
print(f"\nNext steps:")
print(f"  1. cd {ROOT}/firmware")
print(f"  2. pio run            # compile")
print(f"  3. pio run -t upload  # flash")
