#!/usr/bin/env python3
"""
extract_demo_data.py — Trích xuất 100 demo samples từ dataset CSV.

Xuất: firmware/src/demo_sequences.h
Chạy: python firmware/extract_demo_data.py

Chuỗi demo (100 samples):
  BG(50)    → rows 157736–157785
  Fire(50)  → rows 158358–158407

Thứ tự 10 raw sensors trong kDemoData[step][10]:
  [0] CO      [1] H2       [2] Humidity  [3] PM05     [4] PM10
  [5] PM_Typ  [6] PM_Total [7] Temp      [8] UV        [9] VOC
(matches FireDetector::push() parameter order)
"""

import os
import sys
import textwrap
from pathlib import Path

import pandas as pd

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR  = Path(__file__).parent          # firmware/
PROJECT_DIR = SCRIPT_DIR.parent              # Early Fire Alarm/
CSV_PATH    = PROJECT_DIR / "data" / "Indoor Fire Dataset with Distributed Multi-Sensor Nodes.csv"
OUT_PATH    = SCRIPT_DIR / "src" / "demo_sequences.h"

# ── Dataset row ranges (0-indexed) for each phase ─────────────────────────────
# Dataset rows are 1-indexed in plan → subtract 1 for pandas iloc
PHASES = [
    {"name": "Background", "label_int": 0, "row_start": 157736 - 1, "row_end": 157785},   # 50 rows
    {"name": "Fire",       "label_int": 1, "row_start": 158358 - 1, "row_end": 158407},   # 50 rows
]

# ── Column mapping (CSV name → internal name) ─────────────────────────────────
COL_MAP = {
    "CO":       "CO_Room",
    "H2":       "H2_Room",
    "Humidity": "Humidity_Room",
    "PM05":     "PM05_Room",
    "PM10":     "PM10_Room",
    "PM_Typ":   "PM_Room_Typical_Size",
    "PM_Total": "PM_Total_Room",
    "Temp":     "Temperature_Room",
    "UV":       "UV_Room",
    "VOC":      "VOC_Room_RAW",
    "Label":    "ternary_label",
}

SENSOR_KEYS = ["CO", "H2", "Humidity", "PM05", "PM10", "PM_Typ", "PM_Total", "Temp", "UV", "VOC"]


def load_csv() -> pd.DataFrame:
    """Load only the required columns from the large CSV."""
    needed_cols = [COL_MAP[k] for k in SENSOR_KEYS] + [COL_MAP["Label"]]
    print(f"[extract] Reading CSV: {CSV_PATH}")
    print(f"[extract] Columns needed: {needed_cols}")

    # Read in chunks to handle 44 MB file without loading everything if possible
    # Actually, we need iloc by row index, so we need the full file.
    df = pd.read_csv(CSV_PATH, usecols=needed_cols, low_memory=False)
    print(f"[extract] Loaded {len(df):,} rows × {len(df.columns)} columns")
    return df


def extract_phases(df: pd.DataFrame):
    """Extract and concatenate demo phases; return (samples, labels, transitions)."""
    samples     = []   # list of 10-float lists
    labels      = []   # list of int (0=BG, 1=Fire, 2=Nuisance)
    transitions = []   # list of (step_index, phase_name)

    step = 0
    for phase in PHASES:
        subset = df.iloc[phase["row_start"] : phase["row_end"]]
        n = len(subset)
        print(f"[extract] Phase '{phase['name']}': rows {phase['row_start']+1}–{phase['row_end']} → {n} samples")

        transitions.append((step, phase["name"]))

        for _, row in subset.iterrows():
            vals = [float(row[COL_MAP[k]]) for k in SENSOR_KEYS]
            samples.append(vals)
            labels.append(phase["label_int"])

        step += n

    assert len(samples) == 100, f"Expected 100 samples, got {len(samples)}"
    return samples, labels, transitions


def format_float(v: float) -> str:
    """Format float for C source — ensures valid C float literal (e.g. 3.0f not 3f)."""
    # Use %g to strip trailing zeros, but ensure decimal point for integer values
    s = f"{v:.6g}"
    if "." not in s and "e" not in s and "n" not in s:  # integer-like, no decimal point
        s = s + ".0"
    return s + "f"


def write_header(samples, labels, transitions):
    """Write demo_sequences.h."""
    lines = []
    lines.append("/**")
    lines.append(" * demo_sequences.h — AUTO-GENERATED by extract_demo_data.py")
    lines.append(" * DO NOT EDIT MANUALLY.")
    lines.append(" * 100 demo samples extracted from Indoor Fire Dataset:")
    lines.append(" *   BG(50) → Fire(50)")
    lines.append(" *")
    lines.append(" * Sensor order in kDemoData[step][10]:")
    lines.append(" *   [0] CO      [1] H2       [2] Humidity  [3] PM05     [4] PM10")
    lines.append(" *   [5] PM_Typ  [6] PM_Total [7] Temp      [8] UV        [9] VOC")
    lines.append(" */")
    lines.append("")
    lines.append("#pragma once")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append("// ── Demo metadata ─────────────────────────────────────────────────────────────")
    lines.append("constexpr int kDemoTotalSteps = 100;")
    lines.append("")

    # Ground truth labels
    lines.append("// Ground truth label per step: 0=Background, 1=Fire, 2=Nuisance")
    label_vals = ", ".join(str(x) for x in labels)
    lines.append(f"const uint8_t kDemoLabels[100] PROGMEM = {{ {label_vals} }};")
    lines.append("")

    # Transitions
    lines.append("// Transition points: step index where label changes")
    step_vals = ", ".join(str(t[0]) for t in transitions)
    name_vals = ", ".join(f'"{t[1]}"' for t in transitions)
    lines.append(f"constexpr int kDemoTransitionCount = {len(transitions)};")
    lines.append(f"constexpr int kDemoTransitionSteps[{len(transitions)}] = {{ {step_vals} }};")
    lines.append(f"const char* const kDemoTransitionNames[{len(transitions)}] = {{ {name_vals} }};")
    lines.append("")

    # Sensor data
    lines.append("// ── Sensor data ───────────────────────────────────────────────────────────────")
    lines.append("// kDemoData[100][10]: 10 raw sensor values per step (pre-scaler, pre-feature-engineering)")
    lines.append("// FireDetector::push() computes 28 features internally from these 10 values.")
    lines.append(f"// Memory: 100 × 10 × 4 bytes = {100 * 10 * 4} bytes flash")
    lines.append("const float kDemoData[100][10] PROGMEM = {")

    for i, row in enumerate(samples):
        label_name = ["Background", "Fire", "Nuisance"][labels[i]]
        # Check if this is a transition point
        transition_comment = ""
        for step_idx, phase_name in transitions:
            if step_idx == i:
                transition_comment = f"  // ── Phase: {phase_name} ──"
                break

        if transition_comment:
            lines.append(f"  {transition_comment}")

        vals_str = ", ".join(format_float(v) for v in row)
        comma = "," if i < 99 else ""
        lines.append(f"  {{ {vals_str} }}{comma}  // step {i:3d} | GT: {label_name}")

    lines.append("};")
    lines.append("")

    content = "\n".join(lines)
    OUT_PATH.write_text(content, encoding="utf-8")
    print(f"\n[extract] ✓ Written {len(samples)} steps → {OUT_PATH}")
    print(f"[extract]   Labels  : {labels[:5]}...{labels[-5:]}")
    print(f"[extract]   Transitions: {transitions}")
    print(f"[extract]   File size: {OUT_PATH.stat().st_size:,} bytes")


def main():
    if not CSV_PATH.exists():
        print(f"[ERROR] Dataset not found: {CSV_PATH}", file=sys.stderr)
        sys.exit(1)

    df = load_csv()

    # Sanity check: verify label column has expected values
    unique_labels = df[COL_MAP["Label"]].unique()
    print(f"[extract] Unique labels in dataset: {unique_labels}")

    samples, labels, transitions = extract_phases(df)

    # Print stats per phase
    for step_idx, name in transitions:
        print(f"[extract]   Step {step_idx:3d} → '{name}'")

    write_header(samples, labels, transitions)
    print("\n[extract] Done! Run: pio run -e esp32dev-demo")


if __name__ == "__main__":
    main()
